name: flutter_messenger
description: A Flutter messaging app.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.0
  image_picker: ^0.8.7+4
  path_provider: ^2.0.15
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0  # Use an older version  # Added flutter_lints here

flutter:
  uses-material-design: true